### ISSUE TITLE
[IRC] Can't send direct messages to some users

### ISSUE THREAD

**Issue by davide-ceretti** [yougov/pmxbot#74]
If a user has a space in their Slack display name or their Slack display name is empty then pmxbot is unable to deliver direct messages to the user.

Tested on 1119.0.3.

**Comment by jaraco** [comment]
I suspect this issue is actually related to the (legacy) IRC backend, which is what YouGov is still using.

Do you know if there are errors in the logs when pmxbot attempts to route a message to such a user? Can you turn on debug logging (`log level: debug`) and capture the traffic around the time such a message is attempted?

**Comment by davide-ceretti** [comment]
I'll have a look at logs, thanks!

**Comment by jaraco** [comment]
Another thing that might be helpful is to get a user with such a nick to transmit a message (within earshot of pmxbot) while the logs are enabled to see what pmxbot "sees" for those messages.

**Comment by jaraco** [comment]
Given that Slack has dropped support for IRC gateway and this issue was only encountered on Slack, I'm thinking this issue is a won't fix.
